services:
  app:
    container_name: dblocker-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - mosquitto
    environment:
      APP_PORT: 8080
      MQTT_BROKER: tcp://mosquitto:1883
      MQTT_USERNAME: DBL0KER
      MQTT_PASSWORD: '4;1Yf,)`'
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: scm
      DB_PASSWORD: sdfKLJ0)imip
      DB_NAME: dblocker-db
      DB_SSLMODE: disable
      DB_TIMEZONE: UTC
    ports:
      - "8080:8080"

  mosquitto:
    container_name: dblocker-mqtt
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  postgres:
    container_name: dblocker-postgres
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: scm
      POSTGRES_PASSWORD: sdfKLJ0)imip
      POSTGRES_DB: dblocker-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: